name: Run_unit_test

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  Unit-test:
  name: Run unit test in master
  runs-on: ubuntu-latest

  steps:
    - uses: action/checkout@v2
    - uses: action/setup-java@v1
      with: {java-version: 1.8}
    - name: Run unit test
      run: ./gradlew test
